#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff56b6c2
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  7
yabai -m config bottom_padding               7
yabai -m config left_padding                 7
yabai -m config right_padding                7
yabai -m config window_gap                   7

# Spacebar/Sketchybar
yabai -m config external_bar all:26:0

# float windows
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add label="Self Control" app="^Self Control$" manage=off
yabai -m rule --add label="Spotify" app="^Spotify$" manage=off
yabai -m rule --add label="Messages" app="^Messages$" manage=off
# yabai -m rule --add label="iTerm2" app="^iTerm2$" manage=off

yabai -m space 1 --label web
yabai -m space 2 --label code
yabai -m space 3 --label home
yabai -m space 4 --label chat
yabai -m space 5 --label files
yabai -m space 6 --label term

# bind windows to spaces
yabai -m rule --add app="^(Firefox|Safari)$" space=web
yabai -m rule --add app="^Code$" space=code
yabai -m rule --add app="^(Microsoft Teams|WhatsaApp|Messages)$" space=chat
yabai -m rule --add app="^Finder$" display=2 space=files
yabai -m rule --add app="^iTerm2$" display=2 space=term

echo "yabai configuration loaded.."
