#!/usr/bin/env sh

source $HOME/.config/spacebar/colors

spacebar -m config position           top
spacebar -m config height             26
spacebar -m config spacing_left       25
spacebar -m config spacing_right      30
spacebar -m config text_font          "Iosevka Nerd Font:Bold:14.0"
spacebar -m config icon_font          "Hack Nerd Font Mono:Bold:20.0"
spacebar -m config background_color   0xff${BACKGROUND:1}
spacebar -m config foreground_color   0xffffffff

spacebar -m config dnd                      on
spacebar -m config power                    on
spacebar -m config spaces_for_all_displays  on
spacebar -m config display_separator        on

spacebar -m config space_icon_color   0xff${TURQUOISE:1}
spacebar -m config power_icon_color   0xff${YELLOW:1}
spacebar -m config battery_icon_color 0xff${GREEN:1}
spacebar -m config dnd_icon_color     0xff${YELLOW:1}
spacebar -m config clock_icon_color   0xff${PURPLE:1}

spacebar -m config display_separator_icon 
spacebar -m config space_icon_strip         
spacebar -m config power_icon_strip   
spacebar -m config clock_icon        
spacebar -m config dnd_icon          
spacebar -m config clock_format       "%Y-%m-%d %a %R"
# spacebar -m config space_icon         

#spacebar -m config padding_left       20
#spacebar -m config padding_right      20

spacebar -m config title            on
spacebar -m config center_shell on

# spacebar -m config right_shell          on
# spacebar -m config right_shell_icon     
# spacebar -m config right_shell_icon_color   0xff61afef
# spacebar -m config right_shell_command  "whoami"